# Use an official Node.js runtime as a parent image
FROM node:16-slim

# Install Chrome dependencies
RUN apt-get update && apt-get install -y \
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libcups2 \
    libgconf-2-4 \
    libnss3 \
    lsb-release \
    xdg-utils \
    fonts-liberation \
    libx11-xcb1 \
    libxcomposite1 \
    libxrandr2 \
    libxss1 \
    libappindicator1 \
    libxdamage1 \
    libxfixes3 \
    libxcursor1 \
    libgbm1 \
    libgtk-3-0 \
    libxshmfence1 \
    ca-certificates \
    --no-install-recommends

# Install Chrome
RUN apt-get install -y wget
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

# Clean up apt cache and remove downloaded Chrome package
RUN rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && rm google-chrome-stable_current_amd64.deb
    
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose the app on port 3000 (change as necessary)
EXPOSE 5000

# Command to run the Puppeteer app
CMD [ "node", "index.js" ]
